# Generated by Django 4.0 on 2022-01-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/events/pdfs/% Y/% m/% d/'),
        ),
    ]
