# Generated by Django 4.0 on 2022-01-05 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventday',
            old_name='date',
            new_name='event_date',
        ),
    ]
