# Generated by Django 4.0 on 2022-01-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_eventday_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
    ]
