# Generated by Django 4.0 on 2022-01-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/events/banners/% Y/% m/% d/'),
        ),
    ]
