# Generated by Django 4.0 on 2022-01-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_event_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
