# Generated by Django 4.0 on 2022-01-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='uploads/events/docs/% Y/% m/% d/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventdate')),
            ],
        ),
    ]
