# Generated by Django 4.0 on 2022-01-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventdocument'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventdocument',
            unique_together={('event', 'event_date', 'title')},
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventdate')),
            ],
            options={
                'unique_together': {('event', 'event_date', 'title')},
            },
        ),
    ]
