# Generated by Django 4.0 on 2022-01-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventdocument_unique_together_eventlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdocument',
            name='event_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventdate'),
        ),
        migrations.AlterField(
            model_name='eventlink',
            name='event_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventdate'),
        ),
    ]
