# Generated by Django 4.0 on 2022-01-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventdate',
            options={'ordering': ['event_date'], 'verbose_name': 'Event Date', 'verbose_name_plural': 'Event Dates'},
        ),
        migrations.AlterModelOptions(
            name='eventdocument',
            options={'verbose_name': 'Event Document', 'verbose_name_plural': 'Event Documents'},
        ),
        migrations.AlterModelOptions(
            name='eventimagegallery',
            options={'ordering': ['event', 'title'], 'verbose_name': 'Event Gallery', 'verbose_name_plural': 'Event Galleries'},
        ),
        migrations.AlterModelOptions(
            name='eventlink',
            options={'verbose_name': 'Event Link', 'verbose_name_plural': 'Event Links'},
        ),
    ]
