# Generated by Django 4.0 on 2021-12-15 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Adult', 'Adult'), ('Family', 'Family'), ('Student', 'Student')], help_text='Please select the type of membership', max_length=7, verbose_name='Member Type Name')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Membership Year')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Paypal', 'Paypal')], max_length=6)),
                ('payment_date', models.DateField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.membershiptype')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
