# Generated by Django 4.0 on 2021-12-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Membership Year'),
        ),
    ]
