# Generated by Django 4.0 on 2021-12-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_remove_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=24)),
                ('first_name', models.CharField(max_length=24)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=24, null=True)),
                ('state', models.CharField(blank=True, max_length=24, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
    ]
