# Generated by Django 4.0 on 2021-12-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.profile'),
        ),
    ]
