# Generated by Django 4.0 on 2021-12-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_remove_member_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
