# Generated by Django 4.0 on 2022-01-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=65)),
                ('last_name', models.CharField(max_length=65)),
                ('office_held', models.CharField(blank=True, max_length=99, null=True)),
                ('image', models.ImageField(upload_to='uploads/board_members/% Y/% m/% d/')),
            ],
        ),
    ]
