# Generated by Django 4.0 on 2022-01-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_boardmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/board_members/% Y/% m/% d/'),
        ),
    ]
