# Generated by Django 4.0 on 2022-01-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_boardmember_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('level', models.CharField(blank=True, max_length=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/sponsors/% Y/% m/% d/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
