# Generated by Django 4.0 on 2022-01-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer')], default='Winter', max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Board Member', 'verbose_name_plural': 'Board Members'},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['start_date', 'name'], 'verbose_name': ('Sponsor',), 'verbose_name_plural': 'Sponsors'},
        ),
    ]
