# Generated by Django 3.2.11 on 2022-01-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('website', '0007_auto_20220123_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
